version: '3'
services:
  frontend:
    image: drissi2002/frontend-integration:latest
    ports:
      - 4200:4200
    depends_on:
      - backend
    environment:
      - API_URL=http://backend:8080/backend

  backend:
    image: backend-integration:latest
    ports:
      - 8080:8080
    depends_on:
      - db
    environment:
      - SPRING_DATASOURCE_URL=jdbc:postgresql://db:5432/engine
      - SPRING_DATASOURCE_USERNAME=postgres
      - SPRING_DATASOURCE_PASSWORD=98633589

  db:
    image: postgres:latest
    ports:
      - 5432:5432
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=98633589
      - POSTGRES_DB=engine